<?php

namespace App\Http\Controllers;

use App\Book;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreBookRequest;
use App\Services\BookService;
use Illuminate\Http\Request;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, BookService $service)
    {
        $search = $request->query('search');
        $sortOption = $request->query('sort');

        $books = $service->getBookList($search, $sortOption);

        return view('book', compact('books', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Generated by laravel

        // Add unported route response
        return response('Unsupprted route', 418);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\StoreBookRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreBookRequest $request, BookService $service)
    {
        try {
            $service->storeNewBook($request->all());

            return redirect('/books')->with('success', 'New book added.');
        } catch (\Exception $e) {
            return redirect()->back()->withInput()->with('error', 'Failed to add book');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Generated by laravel

        // Add unported route response
        return response('Unsupprted route', 418);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Generated by laravel

        // Add unported route response
        return response('Unsupprted route', 418);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $book = Book::find($id);

        $book->update(['author' => $request['author']]);

        return redirect()->back()->with('message', 'Author has been edited successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Book::destroy($id);

        return redirect()->back()->with('success', 'Book deleted successfully');
    }
}
